### ISSUE TITLE
Incorrect holidays

### ISSUE THREAD

**Issue by papampi** [omid/Persian-Calendar-for-Gnome-Shell#29] opened 2019-10-23 17:57 UTC
First I should thank you for your awesome calendar,

Then, looks like holidays are outdated, 
For example, We have 2 holidays next week on 5th and 7th of Aban, but none marked in it.

**Comment by omid** [comment] 2019-10-23 18:32
Thanks :-)

At least in this specific place, holidays are fine in [the code](https://github.com/omid/Persian-Calendar-for-Gnome-Shell/blob/master/PersianCalendar%40oxygenws.com/events/iranLunar.js#L16)

The problem is the Gregorian-to-Hijri converter which returns 29 days for Safar!
So seems like it's time to change the library to something else!

**Comment by omid** [comment] 2019-10-23 18:38
Most converters out there are based on http://www.staff.science.uu.nl/~gent0113/islam/ummalqura_converter.htm which shows Safar as 29-day month this year!

**Comment by papampi** [comment] 2019-10-23 23:08
I know it must be such a headache to convert these dates while Iranian gov keeps changing them based on watching the moon for Eid-e-Fetr.

**Comment by omid** [comment] 2020-04-22 07:19
Closed because it's duplicate of https://github.com/omid/Persian-Calendar-for-Gnome-Shell/issues/11

**Closed by omid** 2020-04-22 07:19 UTC
